### ISSUE TITLE
Implement Error trait

### ISSUE THREAD

**Issue by tredoe** [rust-lang-nursery/uuid#83]
the trait `std::error::Error` is not implemented for `uuid::ParseError`

**Comment by leoschwarz** [comment]
This is actually implemented in the file `std_support.rs`, however it is only enabled with the `use_std` feature. To enable it with cargo you can add this to your `Cargo.toml` file:

```toml
[dependencies.uuid]
version = "0.4.0"
features = ["use_std"]
```

However this leaves me wondering if `use_std` shouldn't be opt out (enabled by default, but can be disabled) instead of opt in?
